from tools.bash import BASH_TOOLS
from tools.document import DOCUMENT_TOOLS, STRUCTURED_DOCUMENT_HANDLERS
from tools.filesystem import FILESYSTEM_TOOLS, STRUCTURED_FILE_HANDLERS
from tools.http import HTTP_TOOLS, STRUCTURED_HTTP_HANDLERS
from tools.search import SEARCH_TOOLS, STRUCTURED_SEARCH_HANDLERS


TOOLS = [*BASH_TOOLS, *FILESYSTEM_TOOLS, *HTTP_TOOLS, *DOCUMENT_TOOLS, *SEARCH_TOOLS]
STRUCTURED_TOOL_HANDLERS = {
    **STRUCTURED_FILE_HANDLERS,
    **STRUCTURED_HTTP_HANDLERS,
    **STRUCTURED_DOCUMENT_HANDLERS,
    **STRUCTURED_SEARCH_HANDLERS,
}
